.gitignore
composer.json
composer.lock

-Do a `composer install` to get the dependencies

Added PHPUnit with DBUnit extension as a Composer dependency

---

web/schema.sql

This is just the initial DB as is with no data, there will be plenty of changes coming soon.  It was important to me to version this just-in-case.

Add MySQL schema for the "robohome" database

---

.codeclimate.yml
phpmdruleset.xml

Hey Drew,
Jenna here from Code Climate. Sorry for the trouble you were having with this configuration -- it was a bit tricky! It looks like the issue was that the `config` node was missing in your .codeclimate.yml and so we weren't picking up your custom rule set.
Feel free to merge this in. I tested this out on a forked copy of your repo and it seemed to work as expected for me.
Let me know if you have any other questions or if there's anything else I can do to help!
Cheers,
Jenna

Fix for Code Climate config

---

fatfree/javascript/loginWithAmazonScript.js

-"Move the invocation into the parens that contain the function"
-Fixed some formatting while already editing the function

Fix Code Climate complaint in JS file

---

fatfree/app/controllers/LoginController.php

-Handling login should be much cleaner now.  Instead of "manually" generating a 404, I changed to using F3's support for creating HTTP errors and changed the error to a more accurate 401 Unauthorized.

Removed Exit Expressions from LoginController

---

fatfree/app/controllers/LoginController.php

-This bug was introduced when I refactored this class.  Luckily, automated testing is on the way to prevent this from happening again!

Fix bug with new users not being created

---

fatfree/app/Controllers/LoginController.php
fatfree/app/Models/UserModel.php
tests/app/Models/UserModelTest.php

Also removed some unused functions in the `UserModel` class and renamed a function too.

Added unit tests for the UserModel class

---

app/controllers/Controller.php
app/controllers/DeviceController.php
app/controllers/LoginController.php
app/db/IDatabaseConnectionFactory.php
app/db/MySQLDatabaseConnectionFactory.php
app/di/definitions.php
app/models/UserDevicesViewModel.php
index.php

-"New is glue," now using PHP-DI to add dependency injection
-The controller no longer has a dependency on the database!
-Added a factory to create a connection to the database, this will make it easier to swap out in the future if needed
-Only one instance of the F3 framework is created and shared everywhere!
This project now uses PHP-DI: http://php-di.org/

Implemented Dependency Injection Using PHP-DI

---

app/controllers/Controller.php
app/controllers/DeviceController.php
app/controllers/LoginController.php
app/models/DevicesModel.php
app/models/RFDeviceModel.php
app/models/UserDevicesModel.php
app/models/UserDevicesViewModel.php
app/models/UserModel.php
tests/bootstrap.php

PHP will look for variables inside of strings with double quotes.  This isn't the intent most of the time and just makes things less efficient.  I swapped out double quotes for single quotes when possible.

Changed double quotes to single quotes where appropriate

---

composer.json
composer.lock

This also updates all the dependencies as well since I needed to update the lock file.

Adding Code Climate package to Composer

---

app/Http/Controllers/Common/Controller.php
app/Http/Controllers/Web/DevicesController.php
app/Http/Controllers/Web/LoginController.php
routes/web.php
tests/unit/controller/common/ControllerTestCase.php
tests/unit/controller/web/DeviceControllerTest.php
tests/unit/controller/web/LoginControllerTest.php

-Some functionality was (and will be) places in a `common` folder for shared functionality.
-Created `web` folder for functionality belonging to the web.  There will also be an `api` folder to handle functionality for the api.

Separating the web from the API portion of the software

---

tests/unit/model/DeviceTest.php
tests/unit/model/UserTest.php

Using Coveralls makes it easier for me to find where tests are missing.  I'm adding tests to fill in the gaps where possible.

Adding tests where there were gaps in coverage

---

resources/views/devices.blade.php

-Also added max field lengths that correspond to the max field length of the database
-Some column width tweaking to better accommodate the description being displayed

Device description is now displayed

---

app/Providers/DeviceInformationServiceProvider.php

See: https://laravel.com/docs/5.4/providers#deferred-providers

Fix for production having difficulty loading service providers

---

app/Providers/AppServiceProvider.php
tests/unit/mqtt/MessagePublisherTest.php

The more I've learned PHP, Laravel, Mockery, etc. I try to use shorter, more expressive syntax when possible.

Changing some minor ways code can be written

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

These files exist to help best guide users in their experience with contributing to this project by outlining a code of conduct, style guides, checklists for submitting code, and checklists for creating an issue or feature request.

GitHub templates for CONTRIBUTING, PULL_REQUEST_TEMPLATE, and ISSUE_TEMPLATE

---

README.md

Now using Slackin to make joining Slack easy.  Added a badge to the README to make it easy to find and join.
Add a badge that's linked to the Slackin Herokuapp so users can request invitations to join Slack automatically.
Slack provides a great platform to rapidly discuss and get feedback on issues or to inquire about a bug or feature.  Slack also has integrations with GitHub, and Travis to see the status builds.
Viewing the README on GitHub and verifying that a user can get an invitation to join the RoboHome Slack channel after clicking the Slack badge.
Screenshot above shows how the new Slack badge looks and that there are currently 2 or 2 users online.

Add badge for Slack signup

---

.github/PULL_REQUEST_TEMPLATE.md

Add an option for "Enhancement" when selecting the type of change.
Not all changes are bug fixes or features.  Enhancements can be code refactoring, updating the README, changing the build process, changing font sizes, etc.
Hard to test until a new pull request is open to verify the user is presented with the option for "Enhancement."

Change PULL_REQUEST_TEMPLATE to add "Enhancement" as an option

---

README.md

Updated README to include 3 additional steps for setting up a Laravel application and starting a Laravel application.
While these steps are obvious to people with experience with Laravel, they will prove frustrating to figure out for people new to the framework.  The steps are straightforward and will hopefully save some people some effort.
I went through the steps myself to make sure that executing them left me with a running website.

Update README to include more info about setting up and running RoboHome

---

composer.json
composer.lock
phpunit.dusk.xml
phpunit.xml
tests/CreatesApplication.php

This pull request introduces changes to make tests run more quickly by reducing the number of hashing rounds.  It also makes the test results printed to the user more clear by adding the PHPUnit Pretty Result Printer package to this project.
https://github.com/mikeerickson/phpunit-pretty-result-printer
https://twitter.com/taylorotwell/status/943135617466105856
Enhancements to make development on this project easier by making the tests run more quickly, and making test results easier to analyze.
Tests were run many times and a slight speed increase was noted (5-10%).  Also, the display of the results is clearly different and formatted the same  way introduced in the new package.
New format at the top, old format at the bottom.

Test enhancements to improve speed and result clarity

---

.github/PULL_REQUEST_TEMPLATE.md

Added check to require new pull requests are opened from a non-master feature/dev branch.
Contributors would open pull request with their local `master` branch which would cause confusion and makes squashing commits difficult.  All pull request submitted to this repo should have a dedicated branch.

Added clause to PULL_REQUEST_TEMPLATE about creating a branch

---

README.md
StartDockerAndRunTests.sh

Add script to easily run Docker containers and execute all the tests.
Previously, each individual command had to be executed to start and configure the containers and then run the tests.  Now, it's just a single command.
By running the script locally and making sure Docker starts the containers, configures Laravel, and runs the tests.

Add script for running Docker and executing tests

---

composer.json
composer.lock

Updated Composer packages and their dependencies.
Upgrading to the latest and greatest to take advantage of new features and bug fixes.
All the tests passed locally.

Update Composer packages and dependencies

---

app/Http/Controllers/Web/DevicesController.php

Makes generating a flash message and redirecting more succinct.
Cleans up the web `DevicesController` a bit and removes redundant code.
All test passed.

Refactor flash message creation in web devices controller

---

app/Traits/RestExceptionHandler.php
tests/unit/Traits/RestExceptionHandlerTest.php

Add tests for `RestExceptionHandler` trait.  
Testing is important.  The code coverage tool pointed out that the 400 exception didn't have a test around it.  While in theory, it should never get a 400 exception from this trait, it is still possible in the code that it could occur.  This tests all the implemented exceptions so far that result in 400, 401, and 404 errors.
All new and existing unit tests pass.

Add tests for RestExceptionHandler trait

---

app/Http/Controllers/API/DevicesController.php
app/Http/Controllers/API/SettingsController.php
app/Providers/AuthServiceProvider.php
app/Traits/RestExceptionHandler.php
routes/api.php
tests/Unit/Controller/API/DevicesControllerTest.php
tests/Unit/Controller/API/SettingsControllerTest.php
tests/Unit/Traits/RestExceptionHandlerTest.php

This adds protection to the API's `devices/info` endpoint.  Previously, this route was left unprotected.  Now that this project supports Laravel Passport, it's possible to protect this endpoint.  The RoboHome-ESP8266 repository will need to be updated to match this change to request an access token to be able to hit the `info` endpoint.  Also implements the ability to retrieve MQTT configurations values set in the `.env` file from a new API controller.  This removes needing to redundantly store the credentials on the server and the microcontroller to make changing MQTT settings easy.  To access the `devices/info` endpoint and the new `settings/mqtt` endpoint, the `info` scope will need to be used to request the access token.
Security!  All endpoints are now protected using OAuth via …

Support protecting API endpoints with password grants

---

.codeclimate.yml
.env.docker
.env.example
StartDockerAndRunTests.sh
phpunit.xml.dist
web.sh

Added new linter for shell scripts.  Removed checks for static access for PHP Mess Detector since Laravel makes heavy usage of this functionality.
This will now cover shell scripts.  Additionally, it will remove a lot of false positives around static access.  Fixed some settings that were outdated and causing tests to not run right.
It will be verified for correct behavior when this pull request gets reviewed to make sure the checks update accordingly.

Update Code Climate and test settings

---

app/Device.php
app/Http/Controllers/API/DevicesController.php
composer.lock
resources/views/auth/login.blade.php
resources/views/auth/passwords/email.blade.php
resources/views/auth/passwords/reset.blade.php
resources/views/auth/register.blade.php
resources/views/devices.blade.php
resources/views/partials/device-form-body.blade.php
resources/views/partials/edit-device-modal.blade.php
routes/web.php
tests/Unit/Controller/Web/DevicesControllerTest.php
tests/Unit/Model/DeviceTest.php

Updated Composer dependencies to ensure bug and security fixes.  Also performed some minor cleaning like renaming functions, removing unused constructor parameter, and taking advantaging of more streamlined Blade directives introduced in Laravel 5.6.  The only functional difference was updating the verb for an API endpoint from `POST` to `PUT` since it is updating a resource in place and the update function is idempotent.
For general code cleanliness, readability and stability.
All current tests passed.  Testing the app on my local machine is functional as well.

Updated dependencies, cleanup, and use of new functionality

---

composer.json
composer.lock

Minor and major updates to composer packages.
Updating packages are important for security and functionality updates.
All existing unit tests pass.  I also ran through the website too to verify everything is functioning as expected.

Composer dependency updates

---

docker-compose.yml

Added `container_name` attribute to the `docker-compose.yml` file to fix build fail on running 'StartDockerAndRunTests.sh` file. This PR refers to issue #156.
Performed the build again with the applied changes.

modify docker-compose to fix build fail

---

resources/views/devices.blade.php
resources/views/layouts/app.blade.php
resources/views/partials/header.blade.php

Create a general partial.header file including Logo, text, and so on, which can be included in any blade template.
Add RoboHome logo to upper left-hand corner of all pages #151 
Passed original laravel dusk test
- **Home**
- **Login**
- **Forget Password**
- **Reset Password**
- **Devices**

Add RoboHome logo to upper left-hand corner

---

.travis.yml
composer.json
composer.lock

Updating composer dependencies to the latest and greatest to help with security, testing, and maintainability.
Periodically updating composer dependencies is vital for the integrity and long-term success of this codebase.
Andd current unit tests pass.  The website also behaves as expected while testing locally.

Update composer dependencies
