dbudwin/RoboHome-Web

.travis.yml, web/tests/bootstrap.php, web/tests/phpunit.xml
This is the most basic build file I could create.  It can't support anything before PHP 5.6 since the PHPUnit has some dependencies that require PHP >=5.6.
It currently doesn't run any tests.
=> Adding a .travis.yml file to support Travis CI builds

.travis.yml
-Enables sending messages to Slack using the encrypted token.  The Slack channel is #robohome-dev on team robohomeproject.slack.com
-To disable getting emails on every Travis CI build, I turned off email notifications too
-Changed 4 spaces to 2
=> Configure Travis CI notifications

.codeclimate.yml, phpmdruleset.xml
-Added custom ruleset to allow the PHP variable names $db, $f3, and $id
-Added custom ruleset to force methods to be max 25 lines long
Thanks to @leftees at Code Climate for helping me figure out what I did wrong the first time!  This PR will suppressed #16 since it squashed all the commits together.
=> Adding support code Code Climate

web/fatfree/app/controllers/LoginController.php
-This was a hard error to reproduce, but I believe it had to do with the differences in how the `SESSION.user` variable was being checked.  Regardless, this is still a cleaner implementation.
=> Fix for 403 Error that occurred on logout sometimes

.travis.yml, composer.json, composer.lock, tests/phpunit.xml
PHPUnit can support code coverage.  Travis CI will run the coverage report and send the results back to Code Climate.
=> Setting up code coverage reporting

app/Http/Authentication/AmazonLoginAuthenticator.php, app/Http/Authentication/ILoginAuthenticator.php, app/Http/Controllers/Web/LoginController.php, app/Providers/AppServiceProvider.php, tests/unit/authentication/AmazonLoginAuthenticatorTest.php, tests/unit/controller/web/LoginControllerTest.php
The `LoginController` had a rigid dependency on Amazon.  To take advantage of dependency injection I inverted controller by creating a new interface called `ILoginAuthenticator` that the `LoginController` now depends on (instead of performing curl requests against Amazon directly).  There is currently only one implementation of `ILoginAuthenticator` called `AmazonLoginAuthenticator`, but it would be easy now to add the ability to login from other sources too (i.e. Google and/or Facebook) by just swapping dependencies.  This drastically simplified the `LoginController`.  The tests are a lot more logical now too.
=> Refactored the login process

.travis.yml
Travis is building a PR twice (for both a push and a PR trigger), this fix will make it just build once when opening a PR.
Inspired by: http://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda
=> Fix for Travis building PR's twice

app/Http/Authentication/AmazonLoginAuthenticator.php, app/Http/Authentication/ILoginAuthenticator.php, app/Http/Controllers/API/DevicesController.php, app/Http/Kernel.php, app/Http/Middleware/ApiAuthenticator.php, routes/api.php, tests/unit/authentication/AmazonLoginAuthenticatorTest.php, tests/unit/controller/api/DeviceControllerTest.php, tests/unit/controller/common/DeviceControllerTestCase.php, tests/unit/controller/web/DeviceControllerTest.php
This is pretty much just a reimplementation of the existing API before the port to Laravel.  Some aspects that have changed from the F3 version of the API:
-User authentication is handled in the middleware layer, this way the `API/DevicesController` doesn't have a dependency on the `LoginController`
-Uses callback functions to generate list of devices
-Added function to `ILoginAuthenticator` to handle verifying a user from the API
=> Implementing the API for controlling devices

app/Http/Controllers/Web/DevicesController.php, resources/views/devices.blade.php, resources/views/partials/flash-messages.blade.php, tests/unit/controller/web/DeviceControllerTest.php
-Now when a user adds or deletes a device, they'll see a confirmation message at the top of the page
-If a user tries to delete a device they do not own, they'll see an error message
-I also renamed some related test cases to be more clear
=> Add flash messages for device actions

app/Http/Controllers/API/DevicesController.php, app/Http/Controllers/Web/DevicesController.php, app/Http/Globals/DeviceActions.php, app/Http/Globals/FlashMessageLevels.php, app/Http/MQTT/MessagePublisher.php, app/Providers/AppServiceProvider.php, app/Providers/RouteServiceProvider.php, composer.json, composer.lock, resources/views/devices.blade.php, routes/web.php, tests/unit/controller/api/DeviceControllerTest.php, tests/unit/controller/common/DeviceControllerTestCase.php, tests/unit/controller/web/DeviceControllerTest.php, tests/unit/mqtt/MessagePublisherTest.php
-MQTT will be used to publish messages that a microcontroller will be subscribed to
-Any posted URL with the syntax of `/devices/[action]/[id]` will be considered valid (must be all lowercase, see `web.php` for the validation rules)
-Uses ajax to when the "on" or "off" button is clicked to prevent have to reload the page after a message is published
-MD5 is used to generate a client ID (see `AppServiceProvided.php`). While MD5 is not "secure," in this case cryptographic security isn't intended. Generating a "random" string to prevent a potential collision is important.
-Introduced some new constant "global" classes to handle commonly used values for flash messages and actions a device can perform
-Using https://github.com/McFizh/libMQTT from Composer for MQTT support
=> Implemented MQTT message passing for the web and API

app/Http/Controllers/API/DeviceInformation/IDeviceInformation.php, app/Http/Controllers/API/DeviceInformation/RFDeviceInformation.php, app/Http/Controllers/API/DevicesController.php, app/Http/Controllers/Web/DevicesController.php, app/Http/Globals/DeviceTypes.php, app/Providers/DeviceInformationServiceProvider.php, composer.lock, config/app.php, routes/api.php, tests/unit/controller/api/DeviceControllerTest.php, tests/unit/controller/api/deviceInformation/RFDeviceInformationTest.php
Created a new API endpoint called `info(Request $request)` that will call a function called `info($deviceId, $action)` to collect information about a device that would be needed by the microcontroller to control a device.  Currently, the only implementation is for RF devices (`RFDeviceInformation`).  However, to support adding other types of devices, I created a new service provider (`DeviceInformationServiceProvider`) which will bind different instances of `IDeviceInformation` based on the type of device information is being requested for.  This works by passing the `IDeviceInformation` interface as a parameter into the API's `DevicesController`.  When the API's `DevicesController::info(Request $request)` endpoint is executed, the service provider will bind the correct abstraction based …
=> Added ability to request info about a device through the API

app/Http/Controllers/API/DevicesController.php, app/Http/Kernel.php, app/Http/Middleware/AddContentLengthHeader.php, routes/api.php, tests/unit/controller/api/DeviceControllerTest.php
Using chunked transfer encoding as the HTTP response was causing issues for the ESP8266 when hitting the `info` endpoint.  The ESP8266 was trying to read the chunk size as part of the response.  I don't need chunked transfer encoding for this, so reverting to "Content-Length" will work and is probably better for limited capability hardware like the ESP8266.
=> Introduced middleware to add "Content-Length" header to a response

app/Http/Controllers/API/DeviceInformation/ErrantDeviceInformation.php, app/Providers/DeviceInformationServiceProvider.php, tests/unit/controller/api/deviceInformation/ErrantDeviceInformationTest.php
The `ErrantDeviceInformation` class will always return a 400 error.  This class is used as a default implementation of `IDeviceInformation` to be passed into the API's `DevicesController`.  The reason this is necessary is before this change, calling an endpoint (besides `info(Request $request)`) in the API's `DevicesController` would cause a 500 error because there wasn't a value for `IDeviceInformation` it was left unregistered.  This will now more gracefully give the user a 400 error.  Another option to solve this that I approached was to remove `IDeviceInformation` from the API's `DevicesController` altogether and to just call the `info(Request $request)` function directly for each implementation, but I couldn't figure out a graceful way to dynamically pick the correct instance of …
=> Added default implementation for IDeviceInformation

phpmdruleset.xml
Re-adding the custom PHPMD ruleset file referenced in `.codeclimate.yml`.  It got lost during the port to Laravel.  No idea why it was working up until recently (maybe Code Climate has it cached).
=> Added phpmdruleset.xml file for use with Code Climate

resources/views/devices.blade.php
Previously, on smaller screens, the "On" and "Off" buttons would wrap and stack on top of one another.  The table borders between the alternating row colors has also partially disappeared.  Both these issues are now fixed.
=> Fixes for device page layout on mobile

.travis.yml, README.md, app/Device.php, app/Http/Authentication/AmazonLoginAuthenticator.php, app/Http/Authentication/ILoginAuthenticator.php, app/Http/Controllers/API/DeviceInformation/ErrantDeviceInformation.php, app/Http/Controllers/API/DeviceInformation/IDeviceInformation.php, app/Http/Controllers/API/DeviceInformation/RFDeviceInformation.php, app/Http/Controllers/API/DevicesController.php, app/Http/Controllers/Web/DevicesController.php, app/Http/Controllers/Web/LoginController.php, app/Http/MQTT/MessagePublisher.php, app/Http/Middleware/ApiAuthenticator.php, app/Http/Middleware/RedirectIfAuthenticated.php, app/Http/Wrappers/CurlRequest.php, app/Http/Wrappers/ICurlRequest.php, app/RFDevice.php, app/User.php, composer.json, composer.lock, tests/unit/authentication/AmazonLoginAuthenticatorTest.php, tests/unit/controller/api/DeviceControllerTest.php, tests/unit/controller/api/deviceInformation/ErrantDeviceInformationTest.php, tests/unit/controller/api/deviceInformation/RFDeviceInformationTest.php, tests/unit/controller/common/DeviceControllerTestCase.php, tests/unit/controller/web/DeviceControllerTest.php, tests/unit/model/DeviceTest.php, tests/unit/model/UserTest.php, tests/unit/mqtt/MessagePublisherTest.php
-Unless the type is "mixed," it should now be explicitly typed
-This will require PHP 7.1
-Able to remove the `platform` config from `composer.json` since all the dependencies by default work with PHP >=7.1
=> Add parameter and return type hinting when applicable

phpmdruleset.xml
When this project still used F3 instead of Laravel, there was an exception made for the variable `f3` that is no longer needed.
=> Remove exception that was used before switching to Laravel

app/Http/Controllers/Web/DevicesController.php, app/Http/Kernel.php, app/Http/Middleware/RedirectIfGuest.php
Renamed the guest middleware from `RedirectIfAuthenticated` to `RedirectIfGuest` and controller middleware name accordingly.
=> Fixed guest middleware name

app/Http/Kernel.php, app/Providers/AuthServiceProvider.php, resources/views/devices.blade.php, routes/api.php, tests/unit/controller/api/DevicesControllerTest.php
When initially porting this project to Laravel Passport, it was hard to test locally since I didn't have HTTPS set up locally.  When merged, I found a few flaws while trying to link my Amazon Skill to my API that this hopefully fixes.  There were two problems:
1. The CSRF token wasn't being passed when requesting to perform an action.  This fixes a security vulnerability that existed in this program previously.
2. There were no OAuth scopes defined which Amazon's account linking required.  Therefore I created a scope called "control" which is currently serving as a universal scope that has access to anything the API does (which isn't much).
To get account linking working for the RoboHome Amazon skill so it can communicate with the RoboHome API.
The CSRF token passing was tested locally to …
=> OAuth fixes for 3rd party account linking

app/Http/Controllers/API/DevicesController.php, app/Providers/RepositoryServiceProvider.php, app/Repositories/IUserRepository.php, app/Repositories/UserRepository.php, app/User.php, routes/api.php, tests/unit/Repositories/DeviceRepositoryTest.php, tests/unit/Repositories/RepositoryTestCaseWithRealDatabase.php, tests/unit/Repositories/UserRepositoryTest.php, tests/unit/controller/api/DevicesControllerTest.php
There was an oversite where I was trying to use the currently authenticated user to retrieve info about a device.  This is problematic because the `info` method is called by the microcontroller which doesn't have the ability to authenticate users.  I reverted back to the old way where the desired user ID is passed as a query string parameter.  I had to create a `UserRepository` to make this work correctly.
Fix the `info` method in the API so that microcontrollers with minimal processing power can `POST` to the method to get device information without having the login. 
I used Insomnia to hit the `info` method to make sure I got the correct results back for each user ID, device ID, and action.
=> Fix for API's info method

.travis.yml
Coveralls renamed their executable, this fix should enable reporting again.
Coveralls is important for monitoring test coverage of builds.  This will restore that functionality.  This error could be found in the Travis CI logs on builds after updating to satooshi/php-coveralls 2.0 in pull request #128.
```
[0K$ travis_retry php vendor/bin/coveralls -v
Could not open input file: vendor/bin/coveralls
[31;1mThe command "php vendor/bin/coveralls -v" failed. Retrying, 2 of 3.[0m
Could not open input file: vendor/bin/coveralls
[31;1mThe command "php vendor/bin/coveralls -v" failed. Retrying, 3 of 3.[0m
Could not open input file: vendor/bin/coveralls
[31;1mThe command "php vendor/bin/coveralls -v" failed 3 times.[0m
```
The opening of this pull request will re-enable Coveralls reporting.
=> Fix for Coveralls reporting in Travis CI

app/Http/Controllers/API/DeviceInformation/RFDeviceInformation.php, tests/unit/controller/api/deviceInformation/RFDeviceInformationTest.php
When requesting information about an RF device, the pulse length was omitted.  This change will now publish an RF device's pulse length.  A corresponding change needs to be made to the RoboHome-ESP8266 repository to read the `pulse_length` value.  This addresses issue #126.
If a user had a pulse length for an RF device other than the assumed value of 184 (found in the RoboHome-ESP8266 repository) then the device would not be able to be controlled.
Test cases were added to check that the pulse length was published.  I also ran Insomnia against the API endpoint `info` to verify that the pulse length now existed in the JSON response.
=> Publish RF device pulse length

app/Exceptions/Handler.php, app/Http/Controllers/API/DevicesController.php, app/Http/Controllers/Web/DevicesController.php, app/Traits/RestExceptionHandler.php, app/User.php, tests/Browser/DevicesTest.php, tests/unit/controller/api/DevicesControllerTest.php, tests/unit/controller/web/DevicesControllerTest.php, tests/unit/model/UserTest.php
The `doesUserOwnDevice` function in the API's `DevicesController` is no longer needed and should have been removed a while ago in favor of the implementation of `ownsDevice` present in the `User` model.
Clearer more concise use of existing methods.  Also makes testing a bit easier.
Added new unit tests and used Insomnia to hit the `info` endpoint with various different parameters to make sure 200, 401, and 404 errors are produced by the `info` endpoint as expected.
=> Use User's model "ownsDevice" function instead of reimplementation

routes/api.php, tests/Unit/Controller/API/SettingsControllerTest.php
Noticed while developing the ESP-8266 that this should be a `GET` instead of a `POST` since there is no body of the request and we're only asking for information.
Using the correct method is important for readability.  Also makes the ESP-8266 code a bit nicer.
All unit tests pass.
=> Corrected method from POST to GET for MQTT settings

app/Http/Controllers/API/DevicesController.php, app/Http/Controllers/API/SettingsController.php, app/Http/Controllers/API/UsersController.php, app/Http/Controllers/Web/DevicesController.php, app/Http/MQTT/MessagePublisher.php, app/User.php, composer.json, composer.lock, database/factories/UserFactory.php, database/migrations/2018_05_13_190907_add_public_id_to_users_table.php, routes/api.php, tests/Unit/Controller/API/DevicesControllerTest.php, tests/Unit/Controller/API/SettingsControllerTest.php, tests/Unit/Controller/API/UsersControllerTest.php, tests/Unit/Controller/Web/DevicesControllerTest.php, tests/Unit/MQTT/MessagePublisherTest.php
It's never good practice to use your table's primary key as a public facing identifier.  Primary key's should only be used internally within the application itself.  Since this application has a public API, it is time to remove the usage of a `User` model's primary key as a public identifier.  This pull request introduces a database migration to add `public_id` to the `users` table and an API endpoint to access the currently authenticated user's `public_id`.  A corresponding change to the RoboHome-ESP8266 repository will be necessary to take advantage of this update.
Security is the main reason for this change.  Using an autoincremented primary key to identify users leaves the API vulnerable to attack from bots that could easily guess a user's `id`.  With the addition of a `public_id` …
=> Add public facing ID for users

.github/PULL_REQUEST_TEMPLATE.md, app/Device.php, app/Http/Controllers/API/DevicesController.php, app/Http/Controllers/Web/DevicesController.php, app/Http/MQTT/MessagePublisher.php, app/Providers/DeviceInformationServiceProvider.php, app/Providers/RouteServiceProvider.php, app/Repositories/DeviceRepository.php, app/Repositories/IDeviceRepository.php, database/factories/DeviceFactory.php, database/migrations/2018_05_16_014814_add_public_id_to_devices_table.php, resources/views/devices.blade.php, routes/web.php, tests/Unit/Controller/API/DevicesControllerTest.php, tests/Unit/Controller/Web/DevicesControllerTest.php, tests/Unit/MQTT/MessagePublisherTest.php, tests/Unit/Repositories/DeviceRepositoryTest.php
Similar to #144 
It's never good practice to use your table's primary key as a public facing identifier. Primary key's should only be used internally within the application itself. Since this application has a public API, it is time to remove the usage of a `Device` model's primary key as a public identifier. This pull request introduces a database migration to add `public_id` to the `devices` table. A corresponding change to the RoboHome-ESP8266 repository will be necessary to take advantage of this update.
Security is the main reason for this change.  Using an autoincremented primary key to identify users leaves the API vulnerable to attack from bots that could easily guess a user's id. With the addition of a `public_id` field which is a UUID v4 value, it's effectively impossible to …
=> Add public facing ID for devices

app/Http/Controllers/API/DevicesController.php, app/Http/Kernel.php, app/Http/Middleware/ApiVerifyUserOwnsDevice.php, routes/api.php, tests/Unit/Controller/API/DevicesControllerTest.php
Instead of repeating code to check if a user owns a device, it is now implemented as middleware applied to certain API routes.  This also helps to address issue #95.
DRY the API code and make it easier to maintain checking who owns a device.
All existing unit tests pass.  Using Postman, I was able to get the expected JSON response from the affected endpoints.
=> Simplify device ownership via new middleware

app/Http/Controllers/API/DevicesController.php, tests/Unit/Controller/API/DevicesControllerTest.php, tests/Unit/Controller/API/SettingsControllerTest.php, tests/Unit/Controller/API/UsersControllerTest.php
After pull request #146 I noticed that the tests around the API's `DevicesController` could use some cleaning up.  Those tests were the main focus of this pull request.  I simplified it by picking a random device action using reflection to test the `control` function with instead of duplicating tests to test against each device action.  The reasoning here being which device action selected shouldn't affect the outcome of the test.  I also verified the JSON response on non-200 responses from multiple API classes to verify useful error messages were being sent back to the consumer.
Easier to maintain tests and assurances for meaningful error messages in the API.
All new and existing tests pass.
=> Cleanup and make the tests more flexible

resources/views/devices.blade.php, tests/Browser/DevicesTest.php
Resolve #152
- Add confirmation javascript code
- Modify the test case for deletion
- Add a test case for canceling deletion
Add confirmation javascript code. This can be ubiquitous for any confirmation needs by adding class="confirmation".
Confirmation before any un-redoable action is great.
[Add confirmation after clicking "Delete" button](https://github.com/dbudwin/RoboHome-Web/issues/152)
The change causes a js confirmation dialog before actual action. Add dialog check in test cases.
test by laravel dusk `php artisan dusk`
=> Use SweetAlert to add confirmation after clicking delete
